### ISSUE TITLE
Exception: Error: error in the implementation.

### ISSUE THREAD

**Issue by Grant-Fox** [hiruna72/squigualiser#67]
Hello!

I am trying to run the squigualiser reform to get a `.paf` file to visualize my data. I did get the error right before this to add the @SQ to the header which I did and then I ran this CLI `squigualiser reform --sig_move_offset 0 --kmer_length 1 -c --bam sq_test_squig.sam -o test.paf`. 

I received this output/error:
`kmer_length: 1
sig_move_offset: 0
input bam: sq_test_squig.sam
output format: paf
output file: test.paf
Info: Default stride: 5
Traceback (most recent call last):
  File "/PATH/", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/PATH/squigualiser/venv3/lib/python3.13/site-packages/src/__init__.py", line 56, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/PATH/squigualiser/venv3/lib/python3.13/site-packages/src/reform.py", line 228, in run
    raise Exception("Error: error in the implementation. Please report the command with minimal reproducible data. Read_id: {}".format(sam_record.query_name));
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Error: error in the implementation. Please report the command with minimal reproducible data. Read_id: 49174ed0-756e-4be7-a5e4-e00e62ceb5f7`

Please let me know if there is anything more I can provide to help. 

Best,
Grant

**Comment by hiruna72** [comment]
Hey @Grant-Fox,

Thanks for reporting this.
Could you please also provide the following?
1. a slow5 file with the particular read - 49174ed0-756e-4be7-a5e4-e00e62ceb5f7
2. the list of commands you ran to generate sq_test_squig.sam file. Please provide the basecaller version as well.

Thank you again!

**Comment by Grant-Fox** [comment]
Hello @hiruna72,

Slow5, fast5, and blow5 file formats are not supported on github. I am not able to attach them. I did attach a text file that is a copy version of the slow5 file that you requested.

[PAU73218_f2d0d057_ad2e3979_0.47_0.txt.tar.gz](https://github.com/user-attachments/files/17994666/PAU73218_f2d0d057_ad2e3979_0.47_0.txt.tar.gz)

Below are the commands I used to generate `sq_test_squig.sam`.

`buttery-eel -g ~/Downloads/ont-dorado-server/bin/ --config rna_rp4_130bps_sup.cfg -i ~/Downloads/test/blow5_dir/PAU73218_f2d0d057_ad2e3979_0.47_0.blow5 -o test_squig.sam --port 5558 --use_tcp -x cpu --moves_out`

`cd ..`

`cd squigualiser`

`source venv3/bin/activate`

`squigualiser reform --sig_move_offset 0 --kmer_length 1 -c --bam ../test/test_squig.sam -o test.paf`

`echo -e fake_reference'\t'0 > fake_reference.fa.fai`

`samtools view ../test/test_squig.sam -h -t fake_reference.fa.fai -o sq_test_squig.sam`

`squigualiser reform --sig_move_offset 0 --kmer_length 1 -c --bam sq_test_squig.sam -o test.paf`

**Comment by hiruna72** [comment]
Hey @Grant-Fox,

Sorry for the delayed response. 

Unfortunately, the .gz file you shared didn't work.

Can you create a slow5 file like follows,

````
slow5tools get PAU73218_f2d0d057_ad2e3979_0.47_0.blow5 49174ed0-756e-4be7-a5e4-e00e62ceb5f7 -o read.slow5

mv read.slow5 read.slow5.txt
````
and upload the `read.slow5.txt`

Thank you!

**Comment by Grant-Fox** [comment]
Hi @hiruna72,

No problem, attached below is the file you requested. 

One thing to note is that when I ran `slow5tools get PAU73218_f2d0d057_ad2e3979_0.47_0.blow5 49174ed0-756e-4be7-a5e4-e00e62ceb5f7 -o read.slow5`. 

I got this error: 
`[slow5_idx_get::ERROR] Read ID '49174ed0-756e-4be7-a5e4-e00e62ceb5f7' was not found. At src/slow5_idx.c:539
[slow5_get::ERROR] Exiting on error. At src/slow5.c:2529`

To get the read.slow5 for read 49174ed0-756e-4be7-a5e4-e00e62ceb5f7, I ran `slow5tools get *.blow5 49174ed0-756e-4be7-a5e4-e00e62ceb5f7 -o read.slow5`

[read.slow5.txt](https://github.com/user-attachments/files/18201505/read.slow5.txt)

Thank you!

Grant

**Comment by hiruna72** [comment]
Hey @Grant-Fox,

The file you sent does not have a signal.
I assume that this particular read is a split read. Such split reads do not have a signal record in the slow5 file. 
The latest (`0.6.3`) squigualiser skip such split reads.
Can you verify that you are using the latest squigualiser version?

````
python3.8 -m venv venv3
source venv3/bin/activate
pip install --upgrade pip
pip install squigualiser
squigualiser --version
````

**Comment by Grant-Fox** [comment]
Hello @hiruna72 

Thank you for your assistance!

I checked the ran the commands you requested to confirm the version of squigualiser. I am using the lastest version of `0.6.3`.

Pip is also up to date with `24.3.1`
Along with all requirements for `pip install squigualiser` are satisfied

Grant

**Comment by hiruna72** [comment]
Hello @Grant-Fox,

In that case, since the record is not to be found in the slow5 file, can you send me the record in the move table?

```
cat test_squig.sam | grep 49174ed0-756e-4be7-a5e4-e00e62ceb5f7 > move_record.txt
```

**Comment by Grant-Fox** [comment]
@hiruna72 Attached is `move_record.txt` you requested.
[move_record.txt](https://github.com/user-attachments/files/18257042/move_record.txt)

Grant

**Comment by hiruna72** [comment]
Thank you very much. 

I found the bug. In `reform` I filter the split reads using `sp` aux tag in the sam records.
However, this record does not have `sp`. It has `pi` (strange!!!). 
https://github.com/nanoporetech/dorado/blob/release-v0.9/documentation/SAM.md#split-read-tags

I have updated the `dev` branch to include this additional filtering condition.

For now either you can use `dev` branch or filter the split reads as follows,

```
cat sq_test_squig.sam | grep -v pi:Z: > filtered_input_to_reform.sam
```

PS: 
I will tag @Psy-Fer so he can check when he is back whether this is a bug in buttery-eel or dorado-sever 7.4.12+0e5e75c49.
I just tested with dorado standalone 0.8.3 and can confirm that all the split reads have both `sp:i` and `pi:Z` tags.

**Comment by Grant-Fox** [comment]
Thank you for your help @hiruna72! I am using the dev branch and it alleviated my error. The `test.paf` file that it generates is empty because it is skipping the split reads. I will need to try out with another read to see if I get the same results.

Grant

**Comment by hiruna72** [comment]
Hi @Grant-Fox,

Usually, only the the split reads have `sp` and `pi` tags. And the number of split reads in a dataset is very small.
Can you try with slow5-dorado basecaller?
https://github.com/hiruna72/slow5-dorado/releases/tag/v0.8.3

**Comment by Grant-Fox** [comment]
Hi @hiruna72 & @Psy-Fer,

This data was sequenced using the PRO-FLO004 (new direct RNA kit). Could this possible be the issue where when using buttereel, I would be using the incorrect config file? 

Grant

**Comment by Psy-Fer** [comment]
Hey

Nah the issue is I don't add the sp tag to the Sam files because when I wrote that part of the software, that flag didn't exist. Only the pi tag was used for the parent ID.

Anyways, if someone could make an issue on buttery-eel and link this issue I will get to it when I get back from my break.

Cheers,
James

**Comment by Psy-Fer** [comment]
hey @hiruna72 maybe you can help me out

looking to calculate this `sp` tag

here is some raw data I get out of the basecaller for a split read

split read 1

```
channel: 8
daq_offset: -244.0
daq_scaling: 0.1870698481798172
duration: 10050
is_duplex_parent: False
mean_qscore: 12.38630485534668
med_abs_dev: 0.0079876109957695
median: -743.1718139648438
modbase_model_version_id: 
model_stride: 6
model_version_id: dna_r10.4.1_e8.2_400bps_fast@v4.3.0
mux: 2
num_events: 1675
num_minknow_events: 0
read_id: 33de40c6-0c51-4b48-b25f-30e1613dfbc3
run_id: 95efb5e9a97737fb4740d9f8e6163cac19756b7b
sampling_rate: 5000.0
scaling_med_abs_dev: 0.0079876109957695
scaling_median: -743.1718139648438
scaling_version: pa
sequence_length: 613
start_time: 95941863
strand_id: a6888069-8429-49bf-949c-7aba9536d50f
trim_front: 0
trim_rear: 0
trimmed_duration: 10050
trimmed_events: 1675
trimmed_samples: 0

```

split read 2

```
channel: 8
daq_offset: -244.0
daq_scaling: 0.1870698481798172
duration: 19589
is_duplex_parent: False
mean_qscore: 10.307790756225586
med_abs_dev: 0.0079876109957695
median: -743.1718139648438
modbase_model_version_id: 
model_stride: 6
model_version_id: dna_r10.4.1_e8.2_400bps_fast@v4.3.0
mux: 2
num_events: 3264
num_minknow_events: 0
read_id: 33de40c6-0c51-4b48-b25f-30e1613dfbc3
run_id: 95efb5e9a97737fb4740d9f8e6163cac19756b7b
sampling_rate: 5000.0
scaling_med_abs_dev: 0.0079876109957695
scaling_median: -743.1718139648438
scaling_version: pa
sequence_length: 631
start_time: 95951919
strand_id: 3b26a7ba-5549-4214-b6fa-0bf2b0ac62df
trim_front: 0
trim_rear: 0
trimmed_duration: 19589
trimmed_events: 3264
trimmed_samples: 0

```

Can you see what I would need to do to build the sp value?

Cheers,

James

**Comment by hiruna72** [comment]
Hey @Psy-Fer, not sure if this information alone is enough. The signal length of the parent read must be required.

So the doc says,
`sp:i` maps the start of the subread's signal data to the corresponding location in the parent read's signal data.

Deducing the calculation might be easier with some trial and error if you have the output from corresponding ONT version of the basecaller.

**Comment by Psy-Fer** [comment]
Yea true.

I do have the length of the parent signal. Just not sure what's used for the next step.

I'll basecall these reads and see what I can find.
I'll get back to you soon.

James

**Comment by Psy-Fer** [comment]
Here is the output from dorado


```
a6888069-8429-49bf-949c-7aba9536d50f	4	*	0	0	*	*	0	0	ATGTTATGTAACACTTGGTTAGATTACGTATTGCTATGATCAATCTTGAACGAATGAAGAGAGTTGCTTCTTACAGATGAGCAAAGAAATCAGTTTCTCCATGTGCAATTGACTCCTGGTGAAGATGCGGTGAACACTGCTAAAATGACAGCAAGCGATTTAGAAATTGTCATTAAACTTACTTAATAAAAATCAGCATCAGGATTTGAGGACTGACTGCAACTTTGAAAGAAGTTCTACTATGGGTGAATGCTATCAAACAGCATTTCATGGTATAGAGAAATGTTTTGTGCAAGAGTCAATCAATGGGACAAACCTGCCTATCATTAAGAAATTGTCACAGGATTTCCAGCCTTCACCAGCCACCACCCTGATCAGTAGGTTTGACCATGAACATCAAGGAAAGACCCTAACTAACAAAAAGATTATAACTCGCTGATGGCTCAGATGATTGTTAGCATTTTTCAGCAAAAAAGTGTCCTGTAATTAAGGTCTGCACATTTTAAACACAATGCTATTGCACATTTAATAGACTATGTATAGTGTAAACATCAAGCTTTACATGCACTGGGAAACCAAAAAATTTACATGACTCACTGTAAGCAATTGTAAT	$('++*#$*##"""$'$()1%$(%%'*)/*)+2GSGE;<:93;>1592=@S:3AD:;;72(5;B??<?>56*&@:@?F//0@<;JNHKHG=AAESSCC6;CCCFGRJG:JDCAE>AIFFPHCKM:56ACEA=3?CDAA5563>JFE@GHK7EELJHC=@BB3*,035422)+-1-2<;=?:?@;6?FBFA?AG4=B>00--*//&&79-;2<89>?@IFHFGHFIN.-8=E1:2.+))(-/,+,4HMFGFC94403,9@MFC*??;980//,,,23.*)(=D95,,,BL51-.&$&*','*-/778A:7>?>52>;;=%%1+9<76+1/,++*)*,+.().*/27,266@><98@B8;HISIHGLIJGDGEA)+*""%)$$.((%$#"$0//BF@:9'&&*>?57=2..39,<;?3IF=;9ICJ@<?;;9=751;;<6EEA88;8639:0./<7:.'-0---,?F857?>@IMSI?EFJELSISCDGDDDH547:222@?;9FEEESHA@>IEMEHDHDGSSOG>FKIFF6575<2<?@@DB@@E@9=B1-2$$%'22=:698;<77CA<GKLPKA>?CKSSBJGEFSLHNSFIFHNILS@<>A88:+&$"#%	qs:i:12	du:f:2.01	ns:i:10050	ts:i:0	mx:i:2	ch:i:8	st:Z:2024-06-17T08:14:54.900+00:00	rn:i:-1	fn:Z:small.pod5	sm:f:-743.172	sd:f:0.00798761	sv:Z:pa	dx:i:0	RG:Z:95efb5e9a97737fb4740d9f8e6163cac19756b7b_dna_r10.4.1_e8.2_400bps_fast@v4.3.0	pi:Z:33de40c6-0c51-4b48-b25f-30e1613dfbc3	sp:i:0
3b26a7ba-5549-4214-b6fa-0bf2b0ac62df	4	*	0	0	*	*	0	0	TTACAGTGAGTCATGTAAATTTTTTGGTTTCCCAGTGCATGTAAAACTTATGTTTACACTATACATAGTATTTATACTTGCAATAGCATTGTGTTTTAAAAAATGTGCAGATTTTAATTACAGGAGCACTTTTTTTTTTTTTGTTGAAAAATGCTAACAATCATCTGAGCCATCAGAGAGTTTTATAATCTTTTTGTTAGTTAAGGGTTCTTTCCTTCAATGTCATGGCTACTGACTGATCAGGGTGGTGGCTGGTGAAGCTGAGTTGCCTGTGACAATTTCTTAAAATGATAGCAGGTTTTGTCCCATTGATTGACTCTTCTTTGCACAAAGATTTCTCTATACCATGAAATGCTGTTGATAGCATTCACCCATAGTAAAACTCTTTTCAAAGTTGCAGTGAGTCCTCTCAAACCCTGATGCTGATTTTATCTAAGTAGACTTTTATGTAATATTCTAAATAGACTCTGTCAGTTTAGCAGTGTTCACCGCATCTTCACCCAGGAGTCAATTGCACATGGAGAAACTGATTTTCTTTCTAAGTATCTAAGAAGCAACTCTTCATTGGTTCAAGATTGATCATAAGCAAATGGCAA	5A<?FGE=<;?8666>5;>;96?@>&$%16%%*+)&$&%()2/5@1''109:B;CEGH<<7</:8:768.++235+&&,0546B@?AE=76E<B;?S<;5>587,*)+**'#&+407561-'++*/$%)*6*4DEFEH??HH2%%#'/=D@;/..,/%$$'%')&'%+,%&/0'&'+/6<-''/014=<659BCQ87:7156?=93//*&(,./137(%$(76&()*9=F?>B566E+**1-/69M8<<112A103:5=4)42*6091(+/885640-')(&'7;;DLM6FGB-D65=@7SOGF>C>=>O=;;C345A78405<;/**>8:=:6)(33:8A<=5::F@:8+=;000777:BC898'&'.22335>998*$%.-/(/1;D;90DDAAAB8<6'$(1+,3,/%&%<3558-+**:9(((64=+&#$"#"($&,+'+9DEIHJEGD@?@75*.--'#%&)..-.%'.&,?25789::?>:<@?A7DC;;2->>A62/0;AG=86C8;HFSDCAA;C@CC=A>B@B@D4368)(&&&&&+(('.,33,8744:8::3/01%%%.,0/33,+,12012%$$*,-.0+*'""	qs:i:11	du:f:3.9168	ns:i:19584	ts:i:1386	mx:i:2	ch:i:8	st:Z:2024-06-17T08:14:56.911+00:00	rn:i:-1	fn:Z:small.pod5	sm:f:-743.172	sd:f:0.00798761	sv:Z:pa	dx:i:0	RG:Z:95efb5e9a97737fb4740d9f8e6163cac19756b7b_dna_r10.4.1_e8.2_400bps_fast@v4.3.0	pi:Z:33de40c6-0c51-4b48-b25f-30e1613dfbc3	sp:i:10056

```

**Comment by Psy-Fer** [comment]
These are from dorado-server

```
3b26a7ba-5549-4214-b6fa-0bf2b0ac62df	4	*	0	0	*	*	0	0	TTATGCCCTGCTTCCTTGGTTCAGTTACGTATTGCTTACAGTGAGTCATGTAAATTTTTTGGTTTCCCAGTGCATGTAAAACTTATGTTTACACTATACATAGTATTTATACTTGCAATAGCATTGTGTTTTAAAAAATGTGCAGATTTTAATTACAGGAGCACTTTTTTTTTTTTTGTTGAAAAATGCTAACAATCATCTGAGCCATCAGAGAGTTTTATAATCTTTTTGTTAGTTAAGGGTTCTTTCCTTCAATGTCATGGCTACTGACTGATCAGGGTGGTGGCTGGTGAAGCTGAGTTGCCTGTGACAATTTCTTAAAATGATAGCAGGTTTTGTCCCATTGATTGACTCTTCTTTGCACAAAGATTTCTCTATACCATGAAATGCTGTTGATAGCATTCACCCATAGTAAAACTCTTTTCAAAGTTGCAGTGAGTCCTCTCAAACCCTGATGCTGATTTTATCTAAGTAGACTTTTATGTAATATTCTAAATAGACTCTGTCAGTTTAGCAGTGTTCACCGCATCTTCACCCAGGAGTCAATTGCACATGGAGAAACTGATTTTCTTTCTAAGTATCTAAGAAGCAACTCTTCATTGGTTCAAGATTGATCATAAGCAAATGGCAA	%'%%$%',+$#$0&&).'%$%#%*)-'%%,/45965A<?FGE=<;?8666>5;>;96?@>&$%16%%*+)&$&%()2/5@1''109:B;CEGH<<7</:8:768.++235+&&,0546B@?AE=76E<B;?S<;5>587,*)+**'#&+407561-'++*/$%)*6*4DEFEH??HH2%%#'/=D@;/..,/%$$'%')&'%+,%&/0'&'+/6<-''/014=<659BCQ87:7156?=93//*&(,./137(%$(76&()*9=F?>B566E+**1-/69M8<<112A103:5=4)42*6091(+/885640-')(&'7;;DLM6FGB-D65=@7SOGF>C>=>O=;;C345A78405<;/**>8:=:6)(33:8A<=5::F@:8+=;000777:BC898'&'.22335>998*$%.-/(/1;D;90DDAAAB8<6'$(1+,3,/%&%<3558-+**:9(((64=+&#$"#"($&,+'+9DEIHJEGD@?@75*.--'#%&)..-.%'.&,?25789::?>:<@?A7DC;;2->>A62/0;AG=86C8;HFSDCAA;C@CC=A>B@B@D4368)(&&&&&+(('.,33,8744:8::3/01%%%.,0/33,+,12012%$$*,-.0+*'""	qs:i:10	mx:i:2	ch:i:8	rn:i:53620	st:Z:2024-06-16T22:14:54Z	f5:Z:small.pod5ns:i:19589	ts:i:0	sm:f:-743.172	sd:f:0.00798761	sv:Z:pa	du:f:3.9178	pi:Z:33de40c6-0c51-4b48-b25f-30e1613dfbc3	dx:i:0	RG:Z:95efb5e9a97737fb4740d9f8e6163cac19756b7b_dna_r10.4.1_e8.2_400bps_fast@v4.3.0
a6888069-8429-49bf-949c-7aba9536d50f	4	*	0	0	*	*	0	0	ATGTTATGTAACACTTGGTTAGATTACGTATTGCTATGATCAATCTTGAACGAATGAAGAGAGTTGCTTCTTACAGATGAGCAAAGAAATCAGTTTCTCCATGTGCAATTGACTCCTGGTGAAGATGCGGTGAACACTGCTAAAATGACAGCAAGCGATTTAGAAATTGTCATTAAACTTACTTAATAAAAATCAGCATCAGGATTTGAGGACTGACTGCAACTTTGAAAGAAGTTCTACTATGGGTGAATGCTATCAAACAGCATTTCATGGTATAGAGAAATGTTTTGTGCAAGAGTCAATCAATGGGACAAACCTGCCTATCATTAAGAAATTGTCACAGGATTTCCAGCCTTCACCAGCCACCACCCTGATCAGTAGGTTTGACCATGAACATCAAGGAAAGACCCTAACTAACAAAAAGATTATAACTCGCTGATGGCTCAGATGATTGTTAGCATTTTTCAGCAAAAAAGTGTCCTGTAATTAAGGTCTGCACATTTTAAACACAATGCTATTGCACATTTAATAGACTATGTATAGTGTAAACATCAAGCTTTACATGCACTGGGAAACCAAAAAATTTACATGACTCACTGTAAGCAATTGTAAT	$('++*#$*##"""$'$()1%$(%%'*)/*)+2GSGE;<:93;>1592=@S:3AD:;;72(5;B??<?>56*&@:@?F//0@<;JNHKHG=AAESSCC6;CCCFGRJG:JDCAE>AIFFPHCKM:56ACEA=3?CDAA5563>JFE@GHK7EELJHC=@BB3*,035422)+-1-2<;=?:?@;6?FBFA?AG4=B>00--*//&&79-;2<89>?@IFHFGHFIN.-8=E1:2.+))(-/,+,4HMFGFC94403,9@MFC*??;980//,,,23.*)(=D95,,,BL51-.&$&*','*-/778A:7>?>52>;;=%%1+9<76+1/,++*)*,+.().*/27,266@><98@B8;HISIHGLIJGDGEA)+*""%)$$.((%$#"$0//BF@:9'&&*>?57=2..39,<;?3IF=;9ICJ@<?;;9=751;;<6EEA88;8639:0./<7:.'-0---,?F857?>@IMSI?EFJELSISCDGDDDH547:222@?;9FEEESHA@>IEMEHDHDGSSOG>FKIFF6575<2<?@@DB@@E@9=B1-2$$%'22=:698;<77CA<GKLPKA>?CKSSBJGEFSLHNSFIFHNILS@<>A88:+&$"#%	qs:i:12	mx:i:2	ch:i:8	rn:i:53620	st:Z:2024-06-16T22:14:54Z	f5:Z:small.pod5	ns:i:10050	ts:i:0	sm:f:-743.172	sd:f:0.00798761	sv:Z:pa	du:f:2.01	pi:Z:33de40c6-0c51-4b48-b25f-30e1613dfbc3	dx:i:0	RG:Z:95efb5e9a97737fb4740d9f8e6163cac19756b7b_dna_r10.4.1_e8.2_400bps_fast@v4.3
```

**Comment by Psy-Fer** [comment]
I'm starting to think it's not possible from the data the dorado-server is giving me....

**Comment by Psy-Fer** [comment]
this is with dorado-server-7.6.8

```
3b26a7ba-5549-4214-b6fa-0bf2b0ac62df	4	*	0	0	*	*	0	0	TTATGCCCTGCTTCCTTGGTTCAGTTACGTATTGCTTACAGTGAGTCATGTAAATTTTTTGGTTTCCCAGTGCATGTAAAACTTATGTTTACACTATACATAGTATTTATACTTGCAATAGCATTGTGTTTTAAAAAATGTGCAGATTTTAATTACAGGAGCACTTTTTTTTTTTTTGTTGAAAAATGCTAACAATCATCTGAGCCATCAGAGAGTTTTATAATCTTTTTGTTAGTTAAGGGTTCTTTCCTTCAATGTCATGGCTACTGACTGATCAGGGTGGTGGCTGGTGAAGCTGAGTTGCCTGTGACAATTTCTTAAAATGATAGCAGGTTTTGTCCCATTGATTGACTCTTCTTTGCACAAAGATTTCTCTATACCATGAAATGCTGTTGATAGCATTCACCCATAGTAAAACTCTTTTCAAAGTTGCAGTGAGTCCTCTCAAACCCTGATGCTGATTTTATCTAAGTAGACTTTTATGTAATATTCTAAATAGACTCTGTCAGTTTAGCAGTGTTCACCGCATCTTCACCCAGGAGTCAATTGCACATGGAGAAACTGATTTTCTTTCTAAGTATCTAAGAAGCAACTCTTCATTGGTTCAAGATTGATCATAAGCAAATGGCAA	%'%%$%',+$#$0&&).'%$%#%*)-'%%,/45965A<?FGE=<;?8666>5;>;96?@>&$%16%%*+)&$&%()2/5@1''109:B;CEGH<<7</:8:768.++235+&&,0546B@?AE=76E<B;?S<;5>587,*)+**'#&+407561-'++*/$%)*6*4DEFEH??HH2%%#'/=D@;/..,/%$$'%')&'%+,%&/0'&'+/6<-''/014=<659BCQ87:7156?=93//*&(,./137(%$(76&()*9=F?>B566E+**1-/69M8<<112A103:5=4)42*6091(+/885640-')(&'7;;DLM6FGB-D65=@7SOGF>C>=>O=;;C345A78405<;/**>8:=:6)(33:8A<=5::F@:8+=;000777:BC898'&'.22335>998*$%.-/(/1;D;90DDAAAB8<6'$(1+,3,/%&%<3558-+**:9(((64=+&#$"#"($&,+'+9DEIHJEGD@?@75*.--'#%&)..-.%'.&,?25789::?>:<@?A7DC;;2->>A62/0;AG=86C8;HFSDCAA;C@CC=A>B@B@D4368)(&&&&&+(('.,33,8744:8::3/01%%%.,0/33,+,12012%$$*,-.0+*'""	qs:f:10.3078	mx:i:2	ch:i:8	rn:i:53620	st:Z:2024-06-17T08:14:54Z	f5:Z:small.pod5	ns:i:19589	ts:i:0	sm:f:743.172	sd:f:125.194	sv:Z:pa	du:f:3.9178	pi:Z:33de40c6-0c51-4b48-b25f-30e1613dfbc3	dx:i:0	RG:Z:95efb5e9a97737fb4740d9f8e6163cac19756b7b_dna_r10.4.1_e8.2_400bps_fast@v4.3.0
a6888069-8429-49bf-949c-7aba9536d50f	4	*	0	0	*	*	0	0	ATGTTATGTAACACTTGGTTAGATTACGTATTGCTATGATCAATCTTGAACGAATGAAGAGAGTTGCTTCTTACAGATGAGCAAAGAAATCAGTTTCTCCATGTGCAATTGACTCCTGGTGAAGATGCGGTGAACACTGCTAAAATGACAGCAAGCGATTTAGAAATTGTCATTAAACTTACTTAATAAAAATCAGCATCAGGATTTGAGGACTGACTGCAACTTTGAAAGAAGTTCTACTATGGGTGAATGCTATCAAACAGCATTTCATGGTATAGAGAAATGTTTTGTGCAAGAGTCAATCAATGGGACAAACCTGCCTATCATTAAGAAATTGTCACAGGATTTCCAGCCTTCACCAGCCACCACCCTGATCAGTAGGTTTGACCATGAACATCAAGGAAAGACCCTAACTAACAAAAAGATTATAACTCGCTGATGGCTCAGATGATTGTTAGCATTTTTCAGCAAAAAAGTGTCCTGTAATTAAGGTCTGCACATTTTAAACACAATGCTATTGCACATTTAATAGACTATGTATAGTGTAAACATCAAGCTTTACATGCACTGGGAAACCAAAAAATTTACATGACTCACTGTAAGCAATTGTAAT	$('++*#$*##"""$'$()1%$(%%'*)/*)+2GSGE;<:93;>1592=@S:3AD:;;72(5;B??<?>56*&@:@?F//0@<;JNHKHG=AAESSCC6;CCCFGRJG:JDCAE>AIFFPHCKM:56ACEA=3?CDAA5563>JFE@GHK7EELJHC=@BB3*,035422)+-1-2<;=?:?@;6?FBFA?AG4=B>00--*//&&79-;2<89>?@IFHFGHFIN.-8=E1:2.+))(-/,+,4HMFGFC94403,9@MFC*??;980//,,,23.*)(=D95,,,BL51-.&$&*','*-/778A:7>?>52>;;=%%1+9<76+1/,++*)*,+.().*/27,266@><98@B8;HISIHGLIJGDGEA)+*""%)$$.((%$#"$0//BF@:9'&&*>?57=2..39,<;?3IF=;9ICJ@<?;;9=751;;<6EEA88;8639:0./<7:.'-0---,?F857?>@IMSI?EFJELSISCDGDDDH547:222@?;9FEEESHA@>IEMEHDHDGSSOG>FKIFF6575<2<?@@DB@@E@9=B1-2$$%'22=:698;<77CA<GKLPKA>?CKSSBJGEFSLHNSFIFHNILS@<>A88:+&$"#%	qs:f:12.3863	mx:i:2	ch:i:8	rn:i:53620	st:Z:2024-06-17T08:14:54Z	f5:Z:small.pod5	ns:i:10050	ts:i:0sm:f:743.172	sd:f:125.194	sv:Z:pa	du:f:2.01	pi:Z:33de40c6-0c51-4b48-b25f-30e1613dfbc3	dx:i:0	RG:Z:95efb5e9a97737fb4740d9f8e6163cac19756b7b_dna_r10.4.1_e8.2_400bps_fast@v4.3.0
```

**Comment by hiruna72** [comment]
Thanks @Psy-Fer. So basically it is not a oversight in buttery-eel. Just that ONT dorado-server is not outputting `sp:i` tags. Hey @tijyojwad, we just wanted to let ONT know about this issue. Thanks!

**Comment by Psy-Fer** [comment]
I've also added an ask for this to be added to the next dorado-server release on the release notes of v7.6.8
